spring.application.name=EcommerceApp

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=Rohit
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.show-sql=true


#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false


#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1?oracle.net.disableOob=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=10000
spring.jpa.hibernate.ddl-auto=validate


spring.security.user.name = Rohit
spring.security.user.password = 1234
